view.deb5e5dc-fc13-4a79-afba-7df1f78e448a.title=Azure Load Balancer Data Path Availability
view.deb5e5dc-fc13-4a79-afba-7df1f78e448a.desc=Azure Load Balancer Data Path Availability.

view.f388e01c-2cee-4bf8-8b8d-df19da598ca4.title=Azure MySQL Server CPU Usage (%)
view.f388e01c-2cee-4bf8-8b8d-df19da598ca4.desc=Azure MySQL Server CPU Usage (%).

view.56b2eb8f-1e98-4616-816a-803b6342ed5a.title=Azure Virtual Machine CPU Usage (%)
view.56b2eb8f-1e98-4616-816a-803b6342ed5a.desc=Azure Virtual Machine CPU Usage (%).

view.91a7fa4d-df44-4f8e-80b5-ff7327667698.title=Azure SQL Server CPU Usage (%)
view.91a7fa4d-df44-4f8e-80b5-ff7327667698.desc=Azure SQL Server CPU Usage (%).

view.5bf85d53-f9c4-404b-b02a-a72b6b23b1dc.title=Azure SQL Database CPU Usage (%)
view.5bf85d53-f9c4-404b-b02a-a72b6b23b1dc.desc=Azure SQL Database CPU Usage (%).

view.a97249f8-c549-4406-96ec-a89ecc9a538f.title=Azure PostgreSQL Server CPU Usage (%)
view.a97249f8-c549-4406-96ec-a89ecc9a538f.desc=Azure PostgreSQL Server CPU Usage (%).

view.65941230-9686-4521-8f57-8b5ca9acd3bc.title=Azure Virtual Machine Scale Set CPU Usage (%)
view.65941230-9686-4521-8f57-8b5ca9acd3bc.desc=Azure Virtual Machine Scale Sets CPU Usage (%).

view.5dc44f74-4e40-4b46-b07c-21ea55e78fee.title=Azure Web App CPU Usage (%)
view.5dc44f74-4e40-4b46-b07c-21ea55e78fee.desc=Azure Web App CPU Usage (%).

view.9bc1b268-314c-4b01-8b57-dcfcbf634204.title=Azure VMSS Instance CPU Usage (%)
view.9bc1b268-314c-4b01-8b57-dcfcbf634204.desc=Azure Virtual Machine Scale Set Instances CPU Usage (%).

view.583b647e-5904-42f0-bd30-50fd11cefe85.title=Azure Virtual Machines by Sizing Tier
view.583b647e-5904-42f0-bd30-50fd11cefe85.desc=Count of Azure virtual machines by sizing tier.

view.b9b24386-f09b-4204-9759-681ffc3d28ce.title=Azure Virtual Machines Detail
view.b9b24386-f09b-4204-9759-681ffc3d28ce.desc=List of Azure virtual machines with detail.

view.d0ae19a1-7a4b-4b33-b257-d75ddb8cfc94.title=Azure VM CPU Distribution
view.d0ae19a1-7a4b-4b33-b257-d75ddb8cfc94.desc=Azure virtual machines CPU percentage distribution.

view.4f61ff01-87b0-4385-8b8f-db00672580f6.title=Azure Kubernetes Clusters Detail
view.4f61ff01-87b0-4385-8b8f-db00672580f6.desc=List of Azure Kubernetes Clusters with detail.

view.5a804371-d4af-4864-9de8-ea79e183af3e.title=Azure Storage Accounts Detail
view.5a804371-d4af-4864-9de8-ea79e183af3e.desc=List of Azure Storage Accounts with detail.

view.a9084f15-abdb-4c4b-a27d-c81f9c9cc505.title=Azure Virtual Networks Detail
view.a9084f15-abdb-4c4b-a27d-c81f9c9cc505.desc=List of Azure Virtual Networks with detail.