#!/usr/bin/env python3
"""Refresh pricing.py's FALLBACK_PRICES table from the Azure Retail Prices API.

WHY THIS EXISTS
---------------
At collect time `app/pricing.py` prefers the live Azure Retail Prices API
(https://prices.azure.com) and only falls back to the hardcoded
FALLBACK_PRICES table when that endpoint is unreachable. In the air-gapped
Aria Gov environment the Cloud Proxy normally CANNOT reach prices.azure.com,
so FALLBACK_PRICES is effectively the production price source. This script
keeps it fresh.

WHERE TO RUN IT
---------------
Run from a machine WITH internet access (the dev box, or any host that can
reach prices.azure.com over HTTPS) -- NOT the air-gapped collector. Commit the
result, then rebuild/reinstall the pak so the fresh rates ship inside it.

WHAT IT DOES
------------
1. Pulls dedicated-host *consumption* hourly prices across all US Gov + DoD
   regions (reusing pricing._fetch_from_api so the OData filter stays in sync).
2. Collapses hyphen/underscore SKU variants to the canonical underscore form
   and keeps the LOWEST non-zero rate per SKU across regions (widest coverage
   for a shared, region-agnostic fallback table).
3. Rewrites the `FALLBACK_PRICES = { ... }` block in app/pricing.py in place
   and updates the `# Last updated: YYYY-MM-DD` stamp above it.
4. Prints an added / removed / changed summary vs the current table.

SAFETY
------
Never writes an empty table: if the API returns nothing (e.g. run air-gapped
by mistake), it aborts and leaves pricing.py untouched.

USAGE
-----
    python scripts/refresh-fallback-prices.py                 # fetch + rewrite
    python scripts/refresh-fallback-prices.py --dry-run       # fetch + preview
    python scripts/refresh-fallback-prices.py --regions usgovvirginia usgovtexas
"""

import argparse
import datetime
import difflib
import logging
import os
import re
import sys

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger("refresh-fallback-prices")

HERE = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.join(HERE, "..", "Azure-Native-Build", "app")
DEFAULT_PRICING_FILE = os.path.join(APP_DIR, "pricing.py")

# US Gov + DoD regions. Rates are near-identical across them; pulling all and
# keeping the lowest non-zero per SKU maximises SKU coverage for the shared,
# region-agnostic fallback table.
DEFAULT_REGIONS = [
    "usgovvirginia",
    "usgovtexas",
    "usgovarizona",
    "usgoviowa",
    "usdodcentral",
    "usdodeast",
]

# Match the FALLBACK_PRICES literal from its opening line up to the first
# column-0 closing brace (non-greedy, MULTILINE + DOTALL).
_BLOCK_RE = re.compile(r"^FALLBACK_PRICES = \{.*?^\}", re.M | re.S)
_DATE_RE = re.compile(r"^# Last updated: \d{4}-\d{2}-\d{2}\s*$", re.M)


def _import_pricing(pricing_file):
    """Import the target pricing.py as a module so we reuse its exact fetch
    logic and can diff against its current FALLBACK_PRICES."""
    app_dir = os.path.dirname(os.path.abspath(pricing_file))
    if app_dir not in sys.path:
        sys.path.insert(0, app_dir)
    import importlib
    import pricing as pricing_mod
    importlib.reload(pricing_mod)
    return pricing_mod


def fetch_region(pricing_mod, region):
    """Return {canonical_underscore_sku: lowest_nonzero_rate} for one region."""
    raw = pricing_mod._fetch_from_api(region)  # {sku: rate}, incl. variants
    out = {}
    for sku, rate in raw.items():
        try:
            rate = float(rate)
        except (TypeError, ValueError):
            continue
        if rate <= 0:
            continue
        canon = sku.replace("-", "_")
        if canon not in out or rate < out[canon]:
            out[canon] = rate
    return out


def fetch_all(pricing_mod, regions):
    """Merge all regions, keeping the lowest non-zero rate per canonical SKU."""
    merged = {}
    for region in regions:
        prices = fetch_region(pricing_mod, region)
        logger.info("%-16s -> %d SKUs", region, len(prices))
        for sku, rate in prices.items():
            if sku not in merged or rate < merged[sku]:
                merged[sku] = rate
    return merged


def render_table(prices):
    """Render the FALLBACK_PRICES = { ... } Python block (sorted, stable)."""
    lines = ["FALLBACK_PRICES = {",
             "    # Auto-generated by scripts/refresh-fallback-prices.py -- "
             "edit that script, not this block."]
    for sku in sorted(prices, key=str.lower):
        lines.append(f'    "{sku}": {prices[sku]:.4f},')
    lines.append("}")
    return "\n".join(lines)


def diff_summary(old, new):
    old_k, new_k = set(old), set(new)
    added = sorted(new_k - old_k, key=str.lower)
    removed = sorted(old_k - new_k, key=str.lower)
    changed = sorted(
        (k for k in old_k & new_k if round(old[k], 4) != round(new[k], 4)),
        key=str.lower,
    )
    return added, removed, changed


def rewrite(pricing_file, table_text, date_str):
    with open(pricing_file, encoding="utf-8") as fh:
        content = fh.read()

    if len(_BLOCK_RE.findall(content)) != 1:
        raise SystemExit("ERROR: could not locate exactly one FALLBACK_PRICES "
                         "block in %s" % pricing_file)

    new_content = _BLOCK_RE.sub(lambda _m: table_text, content, count=1)
    if _DATE_RE.search(new_content):
        new_content = _DATE_RE.sub(f"# Last updated: {date_str}", new_content, count=1)
    else:
        logger.warning("No '# Last updated:' line found; date stamp not changed.")
    return content, new_content


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--regions", nargs="+", default=DEFAULT_REGIONS,
                    help="Regions to pull (default: all US Gov + DoD).")
    ap.add_argument("--pricing-file", default=DEFAULT_PRICING_FILE,
                    help="Path to pricing.py (default: app/pricing.py).")
    ap.add_argument("--dry-run", action="store_true",
                    help="Fetch and preview the diff; do not write.")
    ap.add_argument("--date", default=None,
                    help="Override the 'Last updated' stamp (YYYY-MM-DD).")
    args = ap.parse_args(argv)

    pricing_file = os.path.abspath(args.pricing_file)
    pricing_mod = _import_pricing(pricing_file)
    current = dict(getattr(pricing_mod, "FALLBACK_PRICES", {}))

    logger.info("Fetching dedicated-host prices from %d region(s)...", len(args.regions))
    merged = fetch_all(pricing_mod, args.regions)

    if not merged:
        raise SystemExit(
            "ERROR: no prices returned (is this host air-gapped, or is "
            "prices.azure.com unreachable?). pricing.py left untouched.")

    added, removed, changed = diff_summary(current, merged)
    logger.info("Fetched %d SKUs. vs current: +%d new, -%d removed, ~%d changed.",
                len(merged), len(added), len(removed), len(changed))
    for k in added:
        logger.info("  + %-24s %.4f", k, merged[k])
    for k in changed:
        logger.info("  ~ %-24s %.4f -> %.4f", k, current[k], merged[k])
    for k in removed:
        logger.info("  - %-24s (was %.4f) -- kept out of new table", k, current[k])

    if removed:
        logger.warning("%d SKU(s) in the current table were NOT returned by the "
                       "API and will be DROPPED. Review the diff before committing.",
                       len(removed))

    date_str = args.date or datetime.date.today().isoformat()
    table_text = render_table(merged)
    old_content, new_content = rewrite(pricing_file, table_text, date_str)

    if old_content == new_content:
        logger.info("No changes -- pricing.py already up to date.")
        return 0

    if args.dry_run:
        diff = difflib.unified_diff(
            old_content.splitlines(keepends=True),
            new_content.splitlines(keepends=True),
            fromfile="pricing.py (current)", tofile="pricing.py (refreshed)")
        sys.stdout.writelines(diff)
        logger.info("Dry run -- no file written.")
        return 0

    with open(pricing_file, "w", encoding="utf-8") as fh:
        fh.write(new_content)
    logger.info("Wrote refreshed FALLBACK_PRICES (%d SKUs, stamped %s) to %s",
                len(merged), date_str, pricing_file)
    logger.info("Next: review `git diff`, commit, then rebuild + reinstall the pak.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
