#This is the default localization file.

#The solution's localized name displayed in UI
DISPLAY_NAME=Microsoft Azure

#The solution's localized description
DESCRIPTION=VMware Aria® Operations Management Pack™ for Microsoft Azure

#The vendor's localized name
VENDOR=DLA Custom