# This is the localized names version. Names now can be described separately based on the version of localized names file

# Symptoms
20001=Azure Virtual Machine CPU utilization is critically high
20002=Azure Virtual Machine CPU utilization is very high
20003=Azure SQL Database DTU utilization is critically high
20004=Azure SQL Database's Data Space Utilization is very high
20005=Azure SQL Database DTU utilization is very high
20006=Azure SQL Database DTU utilization is moderately high
20007=Azure SQL Database's Data Space Utilization is moderately high
20008=Azure SQL Database's Data Space Utilization is critically high
20009=Azure SQL Database DWU utilization is critically high
20010=Azure SQL Database DWU utilization is moderately high
20011=Azure Virtual Machine CPU utilization is moderately high
20012=Azure SQL Database DWU utilization is very high
20013=Azure Virtual Machine is powered off
20014=Azure Virtual Scale Set Instance CPU Utilization is very high.
20015=Azure Virtual Scale Set Instance CPU Utilization is critically high.
20016=Azure Virtual Scale Set Instance CPU Utilization is moderately high.
20017=Azure Application Gateway throughput over 100
20018=Azure Kubernetes Cluster Available Memory is critically low.
20019=Azure Storage Account Availability is fall below 100%
20020=Azure Storage Account Primary Status is not available.
20021=Azure Virtual Scale set Instance state not running
20022=Azure Kubernates Cluster deployment is not Succeeded
20023=Azure Virtual Scale Set CPU Utilization is critically high
20024=Azure Storage Account Provisioning state is not Succeeded.
20025=Azure Virtual Scale Set CPU Utilization is is very high.
20026=Azure Virtual Scale Set CPU Utilization is moderately high.
20027=Azure App Service is not running.



# Alerts
21001=Azure SQL Database DTU Utilization is very high
21002=Azure Virtual Machine CPU Utilization is very high
21003=Azure SQL Database DWU Utilization is very high
21004=Azure SQL Database's Data Space Utilization is very high
21005=Azure Storage Account Availability is fall below 100%"
21006=Azure Virtual Machine is powered off
21007=Azure App Service is not running.
21008=Azure Kubernetes Cluster Available Memory is very low.
21009=Azure Kubernates Cluster deployment is not Succeeded
21010=Azure Storage Account Provisioning state is not Succeeded
21011=Azure Virtual Scale set Instance power state not running
21012=Azure Virtual Scale Set Instance CPU Utilization is very high.
21013=Azure Storage Account Primary Status is not available.
21014=Azure Virtual Scale Set CPU Utilization is is very high.

#Recommendations
22001=Consider upgrading to the next performance tier to increase maximum DTUs, or reducing the load on this data warehouse.
22002=Consider upgrading to the next performance tier to increase maximum DWUs, or reducing the load on this data warehouse.
22003=Consider upgrading to the next performance tier to increase maximum database size, or reducing the size of this database.

# TraversalSpec
800=Azure Subscriptions
801=Azure Regions
